services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j_fails/password  # Replace 'password' with your desired password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs